"""empty message

Revision ID: 94df06725771
Revises: b86e6e731c9e
Create Date: 2019-11-20 10:19:10.847438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94df06725771'
down_revision = 'b86e6e731c9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('members', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('members', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
