"""empty message

Revision ID: ad81c53abe40
Revises: 70afba2a1419
Create Date: 2019-11-22 13:12:09.430037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad81c53abe40'
down_revision = '70afba2a1419'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skills', sa.Column('category', sa.String(length=20), nullable=True))
    op.drop_column('skills', 'mental_physical')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skills', sa.Column('mental_physical', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.drop_column('skills', 'category')
    # ### end Alembic commands ###
