"""empty message

Revision ID: 70afba2a1419
Revises: 94df06725771
Create Date: 2019-11-21 18:07:08.982720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70afba2a1419'
down_revision = '94df06725771'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('mem_skills_held_member_id_fkey', 'mem_skills_held', type_='foreignkey')
    op.drop_constraint('mem_skills_held_skill_id_fkey', 'mem_skills_held', type_='foreignkey')
    op.create_foreign_key(None, 'mem_skills_held', 'skills', ['skill_id'], ['id'], ondelete='cascade')
    op.create_foreign_key(None, 'mem_skills_held', 'members', ['member_id'], ['id'], ondelete='cascade')
    op.drop_constraint('mem_skills_wanted_member_id_fkey', 'mem_skills_wanted', type_='foreignkey')
    op.drop_constraint('mem_skills_wanted_skill_id_fkey', 'mem_skills_wanted', type_='foreignkey')
    op.create_foreign_key(None, 'mem_skills_wanted', 'skills', ['skill_id'], ['id'], ondelete='cascade')
    op.create_foreign_key(None, 'mem_skills_wanted', 'members', ['member_id'], ['id'], ondelete='cascade')
    op.drop_constraint('_m_name_loc_gen_uc', 'members', type_='unique')
    op.create_unique_constraint(None, 'members', ['user_id'])
    op.drop_column('members', 'match_gender')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('match_gender', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'members', type_='unique')
    op.create_unique_constraint('_m_name_loc_gen_uc', 'members', ['name', 'location', 'gender'])
    op.drop_constraint(None, 'mem_skills_wanted', type_='foreignkey')
    op.drop_constraint(None, 'mem_skills_wanted', type_='foreignkey')
    op.create_foreign_key('mem_skills_wanted_skill_id_fkey', 'mem_skills_wanted', 'skills', ['skill_id'], ['id'])
    op.create_foreign_key('mem_skills_wanted_member_id_fkey', 'mem_skills_wanted', 'members', ['member_id'], ['id'])
    op.drop_constraint(None, 'mem_skills_held', type_='foreignkey')
    op.drop_constraint(None, 'mem_skills_held', type_='foreignkey')
    op.create_foreign_key('mem_skills_held_skill_id_fkey', 'mem_skills_held', 'skills', ['skill_id'], ['id'])
    op.create_foreign_key('mem_skills_held_member_id_fkey', 'mem_skills_held', 'members', ['member_id'], ['id'])
    # ### end Alembic commands ###
